---
title: "Präsentation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ggplot2)
library(reshape2)
library(plyr)
library(plotly)
```

## MInfo e.V. Hackathon
### by Team MarHack: Jonny, Quirin, Chris, Luis, Karo

## Data Example

```{r data}
#read data
simulated_data <- data.table(read.csv(file = "./../Data/game_simulation_data.csv"))
simulated_data[1:5,]
```

## Player statistics

```{r player_profile1, include=FALSE}
players = c("Luis", "Karo", "Jonny", "Chris", "Quirin", "Otto")
player_stat <- data.table()

#number of wins and losses
for(i in 1:6){
  games_won <- nrow(simulated_data[(player1_id==players[i] & player1==21) | (player2_id==players[i] & player2==21)])
  games_lost <- nrow(simulated_data[(player1_id==players[i] & player2==21) | (player2_id==players[i] & player1==21)])
  new_entry <- data.table(player=players[i], 
                                    games_won=games_won, 
                                    games_lost=games_lost)
  player_stat <- rbind(player_stat, new_entry)
}
```

```{r player_profile2, include=FALSE}
#mean duration of one game
mean_duration <- data.table()
for (i in 1:length(players)) {
  time_stamps <- simulated_data[(player1==21 | player2==21) & (player1_id==players[i] | player2_id==players[i])]
  mean_tmp <- round((sum(time_stamps[,3])/nrow(time_stamps))/60, digits = 2)
  mean_duration <- rbind(mean_duration, mean_tmp)
}
player_stat <- cbind(player_stat, mean_duration = mean_duration)
names(player_stat)[4] <- "mean_duration"
```

```{r player_profile3, include=FALSE}
#mean number of games per session day
games_per_day <- data.table()
for (i in 1:length(players)) {
  date_data <- simulated_data[(player1==21 | player2==21) & (player1_id==players[i] | player2_id==players[i]), 
                  games_per_date:=.N, by = game_date][games_per_date!="NA"]
  games_per_day <- rbind(games_per_day, mean(date_data[,games_per_date]))
}
player_stat <- cbind(player_stat, games_per_day = games_per_day)
names(player_stat)[5] <- "games_per_day"
```

```{r player_profile4}
player_stat
```

## Player Plots
```{r plot1, echo=FALSE}
win_loose_melt <- melt(data = player_stat[,c(1:3)], id.vars = 'player')
data_sorted <- arrange(win_loose_melt, desc(variable), player) 
data_cumsum <- ddply(data_sorted, "player", transform, label_ypos=cumsum(value))
ggplot(data_cumsum, aes(x = player, y = value, fill = variable)) + 
  geom_bar(stat = 'identity', width = 0.6) + 
  geom_text(aes(y = label_ypos, label = value), vjust = 1.6, color = 'white', size = 3.5) +
  scale_fill_manual(values=c('#66CC99','#CC6666')) +
  guides(fill=guide_legend(title=NULL)) +
  labs(title = "Plot of won and lost games", x = "Player", y = "Number of Games") + 
  theme_minimal()
```

```{r love_matrix, include=FALSE}
result <- c()
for (i in 1:length(players)) {
  for (j in 1:length(players)) {
    new_result <- nrow(simulated_data[(player1==21 | player2==21) & ((player1_id==players[i] & player2_id==players[j]) | (player2_id==players[i] & player1_id==players[j]))])
    result <- append(result, new_result)
  }
}
love_matrix <- matrix(result, byrow = TRUE, nrow = length(players))
colnames(love_matrix) <- players
rownames(love_matrix) <- players
```

```{r love_plot, echo=FALSE}
love_melt <- melt(love_matrix)
names(love_melt) <- c("Player_1", "Player_2", "Amount")
love_plot <- ggplot(love_melt, aes(x = Player_1, y = Player_2)) +
  geom_raster(aes(fill = Amount)) +
  geom_text(aes(label = Amount), color = "white") +
  scale_fill_gradient(low="white", high="#660000") +
  labs(x="", y="", title="Who played with whom") +
  theme_bw()
ggplotly(love_plot)
```
